project:
  type: website
  output-dir: docs

website:
  title: "Catalina Zaza"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: Portfolio
        menu:
          - href: portfolio.qmd
            text: Descripción general
          - href: portfolio/Busemeyer2009.html
            text: Presentation:Busemeyer, 2009

      
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

